### ISSUE TITLE
Failed to start game (missing executable)

### ISSUE THREAD

**Issue by JonathonAshworth** [larsiusprime/tdrpg-bugs#1078]
I'm on Linux x64 (Ubuntu 15.10), playing the Steam version of the game. And it won't launch, citing a missing executable as the reason. I just downloaded the game fresh and verified the integrity of the game cache, all seems to be fine, but the bug persists.

**Comment by larsiusprime** [comment]
When did you last try? I just fixed this bug for a lot of people, it was related to one of the store packages having the wrong file depot configurations.

**Comment by JonathonAshworth** [comment]
Tried it just now. Still not working. I don't think it's updated though. I'm assuming it takes time for updates to propagate through all of Steam's servers? (I'm in Australia).

I'll give it an hour or two and try again.

**Comment by larsiusprime** [comment]
Yeah maybe? Who knows, CDN's and all that nonsense.

**Comment by JonathonAshworth** [comment]
Did a complete reinstall and still happening. Here's what the top level directory looks like, I had a look through the files and there doesn't seem to be any reference to different versions (legacy/original), only one executable etc. Running said executable manually outside of Steam complains about Adobe Air not being installed. Is it possible the new updates aren't downloading for some reason?

![screenshot from 2016-06-17 16-21-53](https://cloud.githubusercontent.com/assets/1953116/16142360/f116a958-34a7-11e6-9330-87ad096fbd24.png)

**Comment by TankFox** [comment]
Exact same issue happening for me on OSX 10.10.5

**Comment by Doldge** [comment]
Copy-Pasta from Steam Forums:

Same deal here. DX was working fine yesterday, after an empty update to day I get the error about no executable. I've tried verify the game cache and re-installing, both with no effect.

1) Country you're in? Ireland
2) Steam language setting? English
3) Operating system + Version? Debian Jessie 8.5
4) Big picture vs normal mode? normal
5) Have you ever touched a beta branch, ever? no
6) Did you buy the game normally or redeem a steam key? redeemed a steam key, purchased from your website around release.
7) Did you participate in the "review" beta branch, ever? no
8) Did you participate in the "test_public" beta branch, ever? no

Additional Info:
Content Build ID: 1184972

Possibly Unrelated:
there's only a single binary in the `bin/` folder (DefendersQuest) which appears to be for the AdobeAir version of the game.

I'm also seeing a bunch of dead sym-links in the `dx/` folder.
I was thinking dx would be directX. but more likely is that they're library files for the new (dx) version of the game (made with Haxe?)?

in which case they probably should be A) linked against something (currently they're trying to link against files in that same folder that don't exist), and B) Linux library's rather than windows? (I'm seeing .ndll files that I would expect to be .so's for nix instead, just a wild guess though).

**Comment by larsiusprime** [comment]
Okay, I wonder if this is because I haven't released 2.01b for linux/mac yet! I assumed that it would not empty out the directory. Let me roll that out here real quick and hopefully that will solve it.

**Comment by larsiusprime** [comment]
Release 2.0.1c, got confirmations it worked. Closing.

**Comment by JonathonAshworth** [comment]
Yep, definitely working! Game is fantastic :)
