### ISSUE TITLE
[DQHD] Upgrade info wrong coloring

### ISSUE THREAD

**Issue by ivanpu** [larsiusprime/tdrpg-bugs#564]
# Basic Info

```
Operating System: ArchLinux
Browser/Download: Download
Demo/Full?      : Demo Version
Version #       : DQ1
```

# Steps to Reproduce:
* Get Azra to level 3
* Open "Team" window
* Select Azra
* Hover "Frenzy" skill

# What I expected to Happen:
Only the bonus part will be colored.

# What happened instead:
The color was shifted: partially coloring what it should, and partially the next word.

# Screenshot
![screenshot from 2015-12-18 22-46-54](https://cloud.githubusercontent.com/assets/2607888/11907565/985af1e2-a5dd-11e5-93f9-367c88c3db11.png)

**Comment by larsiusprime** [comment]
This is fixed in version 0.3.3, please verify.

**Comment by ivanpu** [comment]
Still happens in 0.3.7, but looks more scary now:
![dqhd-0 3 7-green](https://cloud.githubusercontent.com/assets/2607888/12247922/ea6cc14c-b8be-11e5-8eec-bcbae70b2d99.png)

**Comment by larsiusprime** [comment]
Huh, 0.3.6 worked but 0.3.7 is broken? Interesting.

**Comment by larsiusprime** [comment]
This will be fixed in 0.3.9, it was a stupid regression :P
