### ISSUE TITLE
Null Object Reference crash when healer heals

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#679]
First time I had this happen...got everyone in place and leveled up, started the battle at 16x speed, then hit 2 to get ready to frenzy.  Just when I hit the 2 key (non-numpad) on the keyboard, crash.

![dq1hd-crash2](https://cloud.githubusercontent.com/assets/16719964/14640172/9e6a605e-0640-11e6-9373-aa3dee23070a.png)

OS: Win7x64
Download, demo, 0.4.5 HD tryout, at highest res just before 1920x1080, on multimonitor setup, windowed

As you can see, it didn't quite make it into "frenzy cursor" mode before the crash.

BTW I see 3 DOS windows come up on starting the game.  I thought that was from crashdumper, yet I don't see any dumps anywhere after a crash.

**Comment by IBwWG** [comment]
Aha!  I was able to reproduce this, it just happened again.

So I start the game, pick my save, start the level on extreme, level up the characters as shown in the screenshot, click 16X, hit 2, and then this time it didn't seem connected to me hitting 2, but a second or two later (before I had a chance to click to activate the frenzy skill) it crashed again.  Pretty sure I gave the exact same boosts.  Here's the save:

[SAVE_SLOT_1_DEMO.zip](https://github.com/larsiusprime/tdrpg-bugs/files/225935/SAVE_SLOT_1_DEMO.zip)

![dq1hd-crash3](https://cloud.githubusercontent.com/assets/16719964/14640424/ce08016c-0641-11e6-8cb5-731f50b7464d.png)

**Comment by IBwWG** [comment]
Maybe it's more about this particular level on extreme, as was mentioned in #665 about a different level.  Or not really but this level provides the right conditions.

This time, I added everyone wherever, and didn't boost.  Started 16X, waited a bit, hit 2, clicked (frenzy worked) and then a few seconds later it crashed.

![dq1hd-crash4](https://cloud.githubusercontent.com/assets/16719964/14640648/d2d9b004-0642-11e6-80b1-dcd935552410.png)

**Comment by IBwWG** [comment]
I forgot to mention, all the other times, I had paused at the beginning while I set everyone up.

This time I didn't.  I didn't boost anyone, and I didn't hit 2.  I only hit 16X, and very soon after, it crashed.

![dq1hd-crash5](https://cloud.githubusercontent.com/assets/16719964/14640749/48f09eec-0643-11e6-833f-c1e76125bb7a.png)

**Comment by IBwWG** [comment]
Yep, same thing as the previous time, again.

**Comment by IBwWG** [comment]
OK, this time, no boosts, no 2, but I paused, and then once set up I started at 4X speed.  Crashed within 1-2 seconds.

**Comment by IBwWG** [comment]
Maybe he's the culprit:

![dq1hd-crash6](https://cloud.githubusercontent.com/assets/16719964/14640919/1f1347ea-0644-11e6-82fb-341beaf1de7b.png)

This time I didn't pause, boost, or hit 2.  Just placed everyone and sat back.  Crashed within a handful of seconds.

**Comment by IBwWG** [comment]
Yep, I believe it may be healer-related.  I just beat this on Extreme without a healer placed, after all the crashes above with one.

**Comment by IBwWG** [comment]
Indeed, on the next level on extreme, as soon as the healer goes to heal, crash:

![dq1hd-crash7](https://cloud.githubusercontent.com/assets/16719964/14641242/980b32a6-0645-11e6-9c73-ef1bef923a01.png)

**Comment by ManDude** [comment]
Oh wow, and that's the _basic_ healing spell.

**Comment by larsiusprime** [comment]
Were you ever able to reproduce this in an updated build? I believe I fixed this a while back. The latest build should be 0.5.0 I believe.

**Comment by IBwWG** [comment]
I still can't get an updated build to start, unfortunately.  Unless you can tell me when #680 started, so I can find one that's got a fix for this without being broken.

**Comment by larsiusprime** [comment]
Yeah looks like 0.4.9 hasn't uploaded yet. I just pushed it, it should deploy in an hour or so.

**Comment by IBwWG** [comment]
Confirmed that this crash still happens on 0.5.1:

![dq1hd-crash11](https://cloud.githubusercontent.com/assets/16719964/14669653/0d33ad34-06ea-11e6-8b6d-b3fd7f7fbaa8.png)

**Comment by IBwWG** [comment]
Thanks @ManDude BTW, I'll keep that in mind.  :)  So far I've been able to find workarounds, but it's good to know.

**Comment by larsiusprime** [comment]
Okay, good news is this looks like it should be easy to reproduce.

Also... "QUOTE", "COMMA", "PERIOD" ??? Did you pick a keyboard layout other than qwerty? I admit I haven't tested what those look like, I would have expected it to print: `" , .` instead of writing the text out in a big ugly fashion like that.

**Comment by IBwWG** [comment]
Yep, it sure was this time, just one healer and one melee guy.

Yep, I was trying out the dvorak one.  Personally I found it just fine written out that way, it was very explicit.  If it had said `" , .` it probably would have taken me a while to catch on.

**Comment by larsiusprime** [comment]
Hey @IBwWG can you post your save file for me?

**Comment by IBwWG** [comment]
The one I posted earlier should do it, but sure:

[SAVE_SLOT_1_DEMO.zip](https://github.com/larsiusprime/tdrpg-bugs/files/228728/SAVE_SLOT_1_DEMO.zip)

Sorry for the delay.  For some reason I didn't get a notification, I'll have to look into that.

**Comment by larsiusprime** [comment]
No problem! Thanks :)

**Comment by larsiusprime** [comment]
Heh, in the course of importing your file to check the bug I discovered I'd neglected to implement the "fix up demo saves --> full version" feature. Doing that now before anyone reports it!

**Comment by larsiusprime** [comment]
Reproduced in like 15 seconds. Gotta love going off of tester's save files! Now for debugging.

**Comment by larsiusprime** [comment]
Okay, easy fix. The "flavors" array for the healer's attack is null in early game save files, and I've been testing with late-game save files ;P

Put an if not null check in, and we're good!

Expect the fix in 0.5.2

**Comment by IBwWG** [comment]
0.5.2 not out yet BTW?

**Comment by farmboy0** [comment]
Just happened to me (0.5.1 - demo, build 1) (Linux 64-bit)

Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 131
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_backend/native/NativeApplication.hx line 363
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 677
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 529
Called from flixel.FlxGame::step flixel/FlxGame.hx line 662
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx line 1462
Called from flixel.FlxGame::update flixel/FlxGame.hx line 751
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 168
Called from com.leveluplabs.tdrpg.State_Battle::update com/leveluplabs/tdrpg/State_Battle.hx line 867
Called from com.leveluplabs.tdrpg.State_Battle::updateBasic com/leveluplabs/tdrpg/State_Battle.hx line 914
Called from com.leveluplabs.tdrpg.BattleField::update com/leveluplabs/tdrpg/BattleField.hx line 876
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 138
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 138
Called from com.leveluplabs.tdrpg.CreatureSprite::update com/leveluplabs/tdrpg/CreatureSprite.hx line 1487
Called from com.leveluplabs.tdrpg.TDRPGEntitySprite::update com/leveluplabs/tdrpg/TDRPGEntitySprite.hx line 88
Called from flixel.FlxSprite::update flixel/FlxSprite.hx line 586
Called from com.leveluplabs.tdrpg.CreatureSprite::updateAnimation com/leveluplabs/tdrpg/CreatureSprite.hx line 489
Called from com.leveluplabs.tdrpg.TDRPGEntitySprite::updateAnimation com/leveluplabs/tdrpg/TDRPGEntitySprite.hx line 76
Called from flixel.editors.EntitySprite::updateAnimation flixel/editors/EntitySprite.hx line 730
Called from flixel.FlxSprite::updateAnimation flixel/FlxSprite.hx line 594
Called from flixel.animation.FlxAnimationController::update flixel/animation/FlxAnimationController.hx line 88
Called from flixel.animation.FlxAnimation::update flixel/animation/FlxAnimation.hx line 224
Called from flixel.animation.FlxAnimation::set_curFrame flixel/animation/FlxAnimation.hx line 268
Called from flixel.animation.FlxBaseAnimation::set_curIndex flixel/animation/FlxBaseAnimation.hx line 33
Called from flixel.animation.FlxAnimationController::set_frameIndex flixel/animation/FlxAnimationController.hx line 733
Called from flixel.editors.EntitySprite::animationCallback flixel/editors/EntitySprite.hx line 869
Called from com.leveluplabs.tdrpg.DefenderSprite::onSweetFrame com/leveluplabs/tdrpg/DefenderSprite.hx line 634
Called from com.leveluplabs.tdrpg.DefenderSprite::launchAttack com/leveluplabs/tdrpg/DefenderSprite.hx line 2646
Called from com.leveluplabs.tdrpg.DefenderSprite::doHeal com/leveluplabs/tdrpg/DefenderSprite.hx line 3069
Called from com.leveluplabs.tdrpg.CreatureSprite::hitByHeal com/leveluplabs/tdrpg/CreatureSprite.hx line 1900
Called from com.leveluplabs.tdrpg.CreatureSprite::getHealed com/leveluplabs/tdrpg/CreatureSprite.hx line 751
Error : Null Object Reference

**Comment by IBwWG** [comment]
Nice, how'd you get a stack trace?

**Comment by ManDude** [comment]
Run the game from the command prompt.

**Comment by IBwWG** [comment]
Oh, sweet, I wasn't aware it was built that way.  Thanks!

**Comment by farmboy0** [comment]
Didnt realize the issue was already closed so I posted the stacktrace.

**Comment by IBwWG** [comment]
OTOH re: QUOTE COMMA PERIOD, I can see how maybe that's undesirable, since they cover the nice faces of the class reps.  :)

**Comment by larsiusprime** [comment]
FYI -- 0.5.2 should be up now, @IBwWG

**Comment by IBwWG** [comment]
Thanks, I'm all over it like a dragon on some hilarious ancient holy sheep thing :)

**Comment by IBwWG** [comment]
Confirmed, no healer crash on 0.5.2 demo or full.

**Comment by larsiusprime** [comment]
Perfect. Nice to have one of these bugs down...

**Comment by IBwWG** [comment]
Sorry for the flood!  =]
