### ISSUE TITLE
Null Object Reference crash clicking Select (challenge 3) in Bonus popup from map

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#690]
Win7x64, 0.5.2 full:

```
importFromXML() error = 0
FlxUIButton name = movies_btn
FlxUIButton name = music_btn
FlxUIButton name = sfx_btn
FlxUIButton name = party_btn
FlxUIButton name = btn_journal
FlxUIButton name = btn_town
FlxUIButton name = tips_btn
FlxUIButton name = btn_battle
FlxUIButton name = exit_btn
FlxUIButton name = options_btn
FlxUIButton name = menu_btn
FlxUIButton name = bonus_btn
FlxUIButton name = movies_btn
FlxUIButton name = music_btn
FlxUIButton name = sfx_btn
FlxUIButton name = party_btn
FlxUIButton name = btn_journal
FlxUIButton name = btn_town
FlxUIButton name = tips_btn
FlxUIButton name = btn_battle
FlxUIButton name = exit_btn
FlxUIButton name = options_btn
FlxUIButton name = menu_btn
FlxUIButton name = bonus_btn
Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/Na
tiveApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_back
end/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 677
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/Di
splayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObje
ct.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDi
spatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 529
Called from flixel.FlxGame::step flixel/FlxGame.hx line 662
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx lin
e 1462
Called from flixel.FlxGame::update flixel/FlxGame.hx line 751
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 178
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 174
Called from flixel.FlxState::resetSubState flixel/FlxState.hx line 117
Called from com.leveluplabs.tdrpg.Popup_MapPreview::create com/leveluplabs/tdrpg
/Popup_MapPreview.hx line 77
Called from com.leveluplabs.tdrpg.Popup_MapPreview::setupBonus com/leveluplabs/t
drpg/Popup_MapPreview.hx line 476
Called from com.leveluplabs.tdrpg.Popup_MapPreview::showEnemyData com/leveluplab
s/tdrpg/Popup_MapPreview.hx line 944
Called from com.leveluplabs.tdrpg.Popup_MapPreview::showMonsters com/leveluplabs
/tdrpg/Popup_MapPreview.hx line 1185
Called from com.leveluplabs.tdrpg.Popup_MapPreview::addStarRegions com/levelupla
bs/tdrpg/Popup_MapPreview.hx line 431
```

This is using a save I had exported from the original full, then just imported to the HD full.  In the original, this did not cause a crash.

**Comment by larsiusprime** [comment]
Duh, bonus battles don't have star buttons! 

Return from this function early if _stars == null || _stars.length == 0.

Patched, presumed fixed in 0.5.4

**Comment by IBwWG** [comment]
This is happening on Select on challenge 1 now, 0.5.7.

It's possible I did the first two challenges on the non-HD version before switching, that's how I got to 3 before.

```
Called from ApplicationMain::main ApplicationMain.hx line 159
Called from ApplicationMain::create ApplicationMain.hx line 71
Called from lime.app.Application::exec lime/app/Application.hx line 222
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/Na
tiveApplication.hx line 136
Called from lime._backend.native.NativeApplication::handleRenderEvent lime/_back
end/native/NativeApplication.hx line 368
Called from lime.app.Event_Void_Void::dispatch lime/app/Event.hx line 145
Called from *::_Function_2_1 lime/app/Application.hx line 110
Called from lime.app.Application::render lime/app/Application.hx line 762
Called from openfl.display.Stage::render openfl/display/Stage.hx line 677
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/Di
splayObjectContainer.hx line 355
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObje
ct.hx line 251
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDi
spatcher.hx line 237
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 529
Called from flixel.FlxGame::step flixel/FlxGame.hx line 662
Called from com.leveluplabs.tdrpg.Main::update com/leveluplabs/tdrpg/Main.hx lin
e 1481
Called from flixel.FlxGame::update flixel/FlxGame.hx line 751
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 178
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 174
Called from flixel.FlxState::resetSubState flixel/FlxState.hx line 117
Called from com.leveluplabs.tdrpg.Popup_MapPreview::create com/leveluplabs/tdrpg
/Popup_MapPreview.hx line 77
Called from com.leveluplabs.tdrpg.Popup_MapPreview::setupBonus com/leveluplabs/t
drpg/Popup_MapPreview.hx line 479
Called from com.leveluplabs.tdrpg.Popup_MapPreview::showEnemyData com/leveluplab
s/tdrpg/Popup_MapPreview.hx line 948
Called from com.leveluplabs.tdrpg.Popup_MapPreview::showMonsters com/leveluplabs
/tdrpg/Popup_MapPreview.hx line 1189
Called from com.leveluplabs.tdrpg.Popup_MapPreview::addStarRegions com/levelupla
bs/tdrpg/Popup_MapPreview.hx line 433
```

**Comment by IBwWG** [comment]
0.6.0.win7x64, HD mode@1704x960windowed

Same stack trace, still happening trying to select challenge 1.  I think this needs reopening...

**Comment by IBwWG** [comment]
Also 0.6.5 btw but no rush, was just checking in case other changes fixed it as a side-effect.

**Comment by larsiusprime** [comment]
```if (_stars == null)```

um.

```if (_stars == null) return;```

That's better.

**Comment by larsiusprime** [comment]
Fixed in 0.6.6
