### ISSUE TITLE
Healer idle while injured defender is within range

### ISSUE THREAD

**Issue by IBwWG** [larsiusprime/tdrpg-bugs#804]
0.7.8, win7x64, HD mode@1704x960windowed

Injured defender being the other healer in this case:

![dq-healer-not](https://cloud.githubusercontent.com/assets/16719964/15692840/1aebe0fa-2791-11e6-8dbd-c335fb72ed9c.png)

Several seconds went by without a heal.

**Comment by larsiusprime** [comment]
Can you reproduce this consistently?

**Comment by IBwWG** [comment]
I believe I saw it more than once but I haven't tried yet, let me see if I can get the layout later and send it

**Comment by IBwWG** [comment]
0.8.1, win7x64, HD mode@1704x960windowed

Yep, got it again with the above layout:

![dq-healer-not2](https://cloud.githubusercontent.com/assets/16719964/15771745/0cace7a4-296d-11e6-8d22-9c11a2d773db.png)

Seems to happen only on 16X (and maybe only with the healer not selected)--I see a second or two go by without him animating, then pause and take a look.

BTW on 1X I saw for a frame or two Niru just completely disappear in this context too.  Can't remember whether I had the healer selected or not at the time, but I think I did.

**Comment by IBwWG** [comment]
[export-healer-not.zip](https://github.com/larsiusprime/tdrpg-bugs/files/297098/export-healer-not.zip)

Hopefully that has the battle layout saved.  I just quit the battle after the above screenshot.

**Comment by IBwWG** [comment]
The top healer only appears to ever do Holy Light and Zeal, in fact.

**Comment by IBwWG** [comment]
Interestingly, on this level, just use the save and run it at 16X, at the end I got two "Azra survived unharmed" popups.

Also since returning to the latest builds (well, I'm one behind now, but since my jump from 0.6.7) I've noticed that after the battle ends, it continues for a second or so worth of frames before fading out.  Not sure if that was intentional or not, but maybe the double popup I just got is related to that somehow.

**Comment by IBwWG** [comment]
I've noticed this on a few battles since.  He's only doing HL and Zeal, ever.

**Comment by larsiusprime** [comment]
Reproduced.

**Comment by larsiusprime** [comment]
Fixed in 0.8.3

The problem was this:
Healers maintain a list of all friends in range. This list is supposed to be sorted by triage every frame, so that the most wounded defender in range is at position 0. Logically therefore, if the first defender in the list is NOT wounded, then nobody is, and the healer doesn't need to heal.

This only works if you *don't forget to call the sorting function*. Which I did, marked with a big "TODO".

Added the function call, now it works!

**Comment by IBwWG** [comment]
0.8.4, win7x64, HD mode@1704x960windowed

Still getting this...

**Comment by IBwWG** [comment]
![dp-healer-still-not](https://cloud.githubusercontent.com/assets/16719964/15805667/6102e932-2b31-11e6-820b-f75cc40b5280.png)
0.8.4, win7x64, HD mode@1704x960windowed

Healer was there for a few seconds.  You can see the healer is idle.  My dragon in this screenshot has only 20 HP left.  On 1/4 then 1/2 then 1X, I watched as the healer let my dragon die, then paused.  The healer had just cast Holy Light, but all the others were untouched.  I think this is still a bug on 0.8.4 therefore.  It may also have something to do with dragons, but maybe it's a coincidence, since I use them a lot and they don't have armor.

**Comment by IBwWG** [comment]
Actually, here's an interesting thing.  The only healer on the board.  Looks like he's in the middle of casting something, but not aid or group heal.  How does everyone suddenly get healed then?  If you watch closely it seems to correspond with when I click on 1/2X.
![dq-healer-still-not](https://cloud.githubusercontent.com/assets/16719964/15805756/aea0c860-2b33-11e6-9e2e-e298dff96387.gif)

**Comment by ManDude** [comment]
Zeal gives both HP and damages enemies.

**Comment by IBwWG** [comment]
@ManDude Oh...I didn't see that in the description when I moused over during the battle...maybe that's an issue itself too.

However, the idleness bug's definitely still there in 0.8.4.  He's completely idle here while my ranger and knight are half-gone:

![dq-healer-still-not2](https://cloud.githubusercontent.com/assets/16719964/15805810/c7792084-2b34-11e6-8fed-1c3c666e1203.gif)

**Comment by IBwWG** [comment]
@ManDude and it *is* in the description.  Whoops!  Not sure how I missed that the first time.

**Comment by IBwWG** [comment]
Maybe the idleness has to do with the attacking enemies being phased out?  But that's still strange, HP missing is HP missing, he should heal no matter the context, I would think.

**Comment by IBwWG** [comment]
Nope, the Monstrosity+ there is not phased out at the moment, yet the healer stands idle:

![dq-healer-not3](https://cloud.githubusercontent.com/assets/16719964/15806221/66779c56-2b3f-11e6-9ed6-7d91641a40b2.png)

**Comment by IBwWG** [comment]
Although I know you did fix something, because before they would never heal.  Now this only happens sometimes.

**Comment by IBwWG** [comment]
In fact, even when the Fallen Knight+'s came out (they don't phase out) he still stood idle.  Really could have been doing Zeal or something at least here.

**Comment by ManDude** [comment]
Having this issue too. Managed to reproduce it 100% of the time in a modded map

**Comment by JKingweb** [comment]
I am also encountering the same problem:

![image](https://cloud.githubusercontent.com/assets/89590/16137189/ea234c7c-33fe-11e6-8218-210256d0554e.png)

**Comment by mishalunchbox** [comment]
My Healers have ADD too.  And i've noticed that sometimes, even if they're paying attention and doing their job, they won't heal themselves if they're the only ones hurt.

Screenie of Bakal zoning out while his friends die:
http://steamcommunity.com/sharedfiles/filedetails/?id=708995107

I like that my identicon looks like a Space Invaders bunny.

**Comment by IBwWG** [comment]
Still there on 2.0.4c/win7x64, healer idle while ranger nearby is at half health.

**Comment by ManDude** [comment]
Doesn't happen at the normal priority, only healing priority or attack priority.

**Comment by IBwWG** [comment]
Huh, I didn't even notice that I'd set a priority.  Well, that's ironic, that no healing happens when healing is the priority :)

**Comment by ClaudioBasckeira** [comment]
Healing priority seems to be the default, since I don't remember setting anything for them either and it's the first on the list. I can confirm the depressed-healers-bug happening here too. Still trying to figure out the circumstances to reproduce it adequately.

**Comment by IBwWG** [comment]
Just had something similar with a knight not attacking anyone, despite adjacent enemies not being phased out or dark, and recharged skills.  Really hard to reproduce though.
