### ISSUE TITLE
In Old Graphics Mode, any battle with the Sorceress as the hero crashes on entry.

### ISSUE THREAD

**Issue by dqhol** [larsiusprime/tdrpg-bugs#962]

**Comment by larsiusprime** [comment]
What version? I believe I fixed this in 0.9.3

**Comment by dqhol** [comment]
Oh, I thought I was on the most recent. Looks like the update server put out 9.3 shortly after I got 9.2, sorry!

**Comment by dqhol** [comment]
Okay, updated to 0.9.3 and it's... still crashing on old graphics mode. Reopening.

**Comment by larsiusprime** [comment]
Right you are, still broken even in 0.9.7.

Fixed in 0.9.8
